# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/jgoulet/dev_UI/proxy_tool/ui/proxyTool_window.ui'
#
# Created: Tue Sep 20 13:34:23 2016
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(275, 193)
        MainWindow.setMaximumSize(QtCore.QSize(275, 193))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_scinder_mesh = QtGui.QPushButton(self.centralwidget)
        self.button_scinder_mesh.setObjectName("button_scinder_mesh")
        self.gridLayout_2.addWidget(self.button_scinder_mesh, 2, 0, 1, 1)
        self.button_rename_geo = QtGui.QPushButton(self.centralwidget)
        self.button_rename_geo.setObjectName("button_rename_geo")
        self.gridLayout_2.addWidget(self.button_rename_geo, 0, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.button_soft_reset_loops = QtGui.QPushButton(self.centralwidget)
        self.button_soft_reset_loops.setObjectName("button_soft_reset_loops")
        self.gridLayout.addWidget(self.button_soft_reset_loops, 1, 0, 1, 1)
        self.button_add_loop = QtGui.QPushButton(self.centralwidget)
        self.button_add_loop.setObjectName("button_add_loop")
        self.gridLayout.addWidget(self.button_add_loop, 0, 0, 1, 1)
        self.button_view_wip = QtGui.QPushButton(self.centralwidget)
        self.button_view_wip.setObjectName("button_view_wip")
        self.gridLayout.addWidget(self.button_view_wip, 0, 1, 1, 1)
        self.button_empty_loop_list = QtGui.QPushButton(self.centralwidget)
        self.button_empty_loop_list.setObjectName("button_empty_loop_list")
        self.gridLayout.addWidget(self.button_empty_loop_list, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 275, 25))
        self.menubar.setObjectName("menubar")
        self.menuTooltips_On_Off = QtGui.QMenu(self.menubar)
        self.menuTooltips_On_Off.setObjectName("menuTooltips_On_Off")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_add_loop = QtGui.QAction(MainWindow)
        self.action_add_loop.setObjectName("action_add_loop")
        self.action_view_wip = QtGui.QAction(MainWindow)
        self.action_view_wip.setObjectName("action_view_wip")
        self.action_soft_reset_loops = QtGui.QAction(MainWindow)
        self.action_soft_reset_loops.setObjectName("action_soft_reset_loops")
        self.action_empty_loop_list = QtGui.QAction(MainWindow)
        self.action_empty_loop_list.setObjectName("action_empty_loop_list")
        self.action_scinder_mesh = QtGui.QAction(MainWindow)
        self.action_scinder_mesh.setObjectName("action_scinder_mesh")
        self.action_rename_geo_from_parent = QtGui.QAction(MainWindow)
        self.action_rename_geo_from_parent.setObjectName("action_rename_geo_from_parent")
        self.action_tooltips_activation = QtGui.QAction(MainWindow)
        self.action_tooltips_activation.setObjectName("action_tooltips_activation")
        self.menubar.addAction(self.menuTooltips_On_Off.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.button_add_loop, QtCore.SIGNAL("released()"), self.action_add_loop.trigger)
        QtCore.QObject.connect(self.button_empty_loop_list, QtCore.SIGNAL("released()"), self.action_empty_loop_list.trigger)
        QtCore.QObject.connect(self.button_scinder_mesh, QtCore.SIGNAL("released()"), self.action_scinder_mesh.trigger)
        QtCore.QObject.connect(self.button_soft_reset_loops, QtCore.SIGNAL("released()"), self.action_soft_reset_loops.trigger)
        QtCore.QObject.connect(self.button_rename_geo, QtCore.SIGNAL("released()"), self.action_rename_geo_from_parent.trigger)
        QtCore.QObject.connect(self.button_view_wip, QtCore.SIGNAL("released()"), self.action_view_wip.trigger)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Quick proxy tool window", None, QtGui.QApplication.UnicodeUTF8))
        self.button_scinder_mesh.setText(QtGui.QApplication.translate("MainWindow", "Scinder Mesh", None, QtGui.QApplication.UnicodeUTF8))
        self.button_rename_geo.setText(QtGui.QApplication.translate("MainWindow", "rename geometry from parent", None, QtGui.QApplication.UnicodeUTF8))
        self.button_soft_reset_loops.setText(QtGui.QApplication.translate("MainWindow", "soft reset loops", None, QtGui.QApplication.UnicodeUTF8))
        self.button_add_loop.setText(QtGui.QApplication.translate("MainWindow", "add loop", None, QtGui.QApplication.UnicodeUTF8))
        self.button_view_wip.setText(QtGui.QApplication.translate("MainWindow", "view wip", None, QtGui.QApplication.UnicodeUTF8))
        self.button_empty_loop_list.setText(QtGui.QApplication.translate("MainWindow", "empty loop list", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTooltips_On_Off.setTitle(QtGui.QApplication.translate("MainWindow", "Tooltips On/Off", None, QtGui.QApplication.UnicodeUTF8))
        self.action_add_loop.setText(QtGui.QApplication.translate("MainWindow", "add loop", None, QtGui.QApplication.UnicodeUTF8))
        self.action_add_loop.setToolTip(QtGui.QApplication.translate("MainWindow", "Will add curreent selected edges to the loop list", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_wip.setText(QtGui.QApplication.translate("MainWindow", "view wip", None, QtGui.QApplication.UnicodeUTF8))
        self.action_view_wip.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Will select your</p><p>current loop list</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.action_soft_reset_loops.setText(QtGui.QApplication.translate("MainWindow", "soft reset loops", None, QtGui.QApplication.UnicodeUTF8))
        self.action_soft_reset_loops.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>This will return your current loop</p><p>selection <span style=\" font-weight:600;\">AND </span>then <span style=\" text-decoration: underline;\">wipe</span> your loop list.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.action_empty_loop_list.setText(QtGui.QApplication.translate("MainWindow", "empty_loop_list", None, QtGui.QApplication.UnicodeUTF8))
        self.action_empty_loop_list.setToolTip(QtGui.QApplication.translate("MainWindow", "This will wipe your loop list.", None, QtGui.QApplication.UnicodeUTF8))
        self.action_scinder_mesh.setText(QtGui.QApplication.translate("MainWindow", "scinder mesh", None, QtGui.QApplication.UnicodeUTF8))
        self.action_scinder_mesh.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>This will split geometry with your loop selection </p><p>and rename everything that comes out of this.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.action_rename_geo_from_parent.setText(QtGui.QApplication.translate("MainWindow", "rename geometry from parent", None, QtGui.QApplication.UnicodeUTF8))
        self.action_rename_geo_from_parent.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Select the groups of the geometry</p><p>you would like to rename. ex:</p><p>\'pSphere_01_proxy\'</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.action_tooltips_activation.setText(QtGui.QApplication.translate("MainWindow", "tooltips activation", None, QtGui.QApplication.UnicodeUTF8))

